"""Navigation and explicit export join for whole-program catalog spellings.

The six owner modules classify audited constructions by dominant mechanic;
``entries`` owns callable-free provenance shells.  This package initializer is
the sole join between those namespaces.  It does not synthesize functions,
dispatch by family or ID, construct programs, or attach catalog identity to a
program.

This module flat-exports all canonical development stubs, implemented presets,
and true-alias spellings explicitly.  The sole deprecated compatibility spelling remains qualified as
``ca.catalog.machina.extended_mobile_automaton``.  Root ``ca`` exposes this
namespace but does not flatten any catalog spelling.
"""

from __future__ import annotations

from . import automata, criteria, dynamica, entries, machina, media, substitua
from .automata import (
    alternating_partition_local_evolution,
    arithmetic_iteration,
    asynchronous_local_state_automaton,
    cellular_automaton_2d,
    cellular_automaton_3d,
    continuous_cellular_automaton,
    coupled_field_mobile_locus_evolution,
    digit_reversal_map,
    driven_relaxation,
    eca,
    elementary_cellular_automaton,
    generalized_mobile_automaton,
    higher_color_totalistic_cellular_automaton,
    history_dependent_agent_game,
    iterated_map,
    lattice_cellular_automaton,
    moore_cellular_automaton,
    multicolor_cellular_automaton,
    multi_active_local_rewrite,
    mutable_rule_local_automaton,
    piecewise_integer_map,
    population_evolutionary_search,
    quiescent_cellular_automaton,
    symmetric_cellular_automaton,
    synchronous_local_state_transform,
    three_color_totalistic_cellular_automaton,
    totalistic_cellular_automaton,
    weighted_network_state_update,
)
from .criteria import (
    finite_model_satisfaction,
    geometric_embedding_relation,
    global_equation_relation,
    inverse_local_system_reconstruction,
    local_constraint_system,
    local_factor_weighted_relation,
    local_satisfaction_relation,
    program_randomization_test,
    seeded_template_constraint_system,
    stochastic_local_search,
    template_constraint_system,
    weighted_history_sum_relation,
)
from .dynamica import (
    continuous_event_dynamics,
    ordinary_differential_flow,
    partial_differential_relation,
    pde,
)
from .machina import (
    enumerative_semidecision,
    finite_gate_circuit,
    mobile_automaton,
    mobile_head_grid_rewrite,
    nearest_neighbor_retrieval,
    neighbor_updating_mobile_automaton,
    priority_dovetailed_oracle_construction,
    recursive_function_evaluator,
    register_machine,
    stored_program_random_access_machine,
    turing_machine,
    turing_machine_2d,
)
from .media import (
    aligned_xor_stream_transduction,
    constant_digit_register,
    digit_emitting_register_transduction,
    error_diffusion_transform,
    event_provenance_causal_network,
    hash_index_transform,
    history_reference_record_transduction,
    maximal_run_record_transduction,
    nested_interval_symbol_transduction,
    orthogonal_basis_coefficient_transform,
    predictive_residual_transduction,
    probabilistic_transition_model_fitting,
    recursive_uniform_region_decomposition,
    sampled_causal_order_network,
    look_and_say,
    weighted_prefix_block_transduction,
)
from .substitua import (
    append_only_sequence_generation,
    constant_digit_sequence,
    context_dependent_substitution_2d,
    context_dependent_substitution,
    continued_fraction_substitution,
    creation_destruction_substitution,
    cyclic_tag_system,
    first_passage_aggregation,
    front_delete_rear_append_system,
    geometric_substitution,
    global_score_sequential_placement,
    history_dependent_growth_rewrite,
    indexed_history_recurrence,
    iterated_erasure_process,
    local_graph_rewrite,
    moving_frontier_shell_accretion,
    multiway_rewrite,
    multiway_system,
    neighbor_dependent_substitution,
    neighbor_independent_substitution,
    network_rewrite,
    number_theoretic_filtering,
    parallel_independent_substitution,
    parallel_network_rewrite,
    random_functional_graph_construction,
    recursive_sequence,
    sequential_substitution,
    structural_pattern_rewrite,
    substitution_system_2d,
    symbolic_system,
    tag_system,
    variable_index_recursive_sequence,
)


__all__ = (
    "entries",
    "automata",
    "substitua",
    "machina",
    "media",
    "criteria",
    "dynamica",
    "alternating_partition_local_evolution",
    "arithmetic_iteration",
    "asynchronous_local_state_automaton",
    "cellular_automaton_2d",
    "cellular_automaton_3d",
    "continuous_cellular_automaton",
    "coupled_field_mobile_locus_evolution",
    "digit_reversal_map",
    "driven_relaxation",
    "eca",
    "elementary_cellular_automaton",
    "generalized_mobile_automaton",
    "higher_color_totalistic_cellular_automaton",
    "history_dependent_agent_game",
    "iterated_map",
    "lattice_cellular_automaton",
    "moore_cellular_automaton",
    "multicolor_cellular_automaton",
    "multi_active_local_rewrite",
    "mutable_rule_local_automaton",
    "piecewise_integer_map",
    "population_evolutionary_search",
    "quiescent_cellular_automaton",
    "symmetric_cellular_automaton",
    "synchronous_local_state_transform",
    "three_color_totalistic_cellular_automaton",
    "totalistic_cellular_automaton",
    "weighted_network_state_update",
    "append_only_sequence_generation",
    "constant_digit_sequence",
    "context_dependent_substitution_2d",
    "context_dependent_substitution",
    "continued_fraction_substitution",
    "creation_destruction_substitution",
    "cyclic_tag_system",
    "first_passage_aggregation",
    "front_delete_rear_append_system",
    "geometric_substitution",
    "global_score_sequential_placement",
    "history_dependent_growth_rewrite",
    "indexed_history_recurrence",
    "iterated_erasure_process",
    "local_graph_rewrite",
    "moving_frontier_shell_accretion",
    "multiway_rewrite",
    "neighbor_dependent_substitution",
    "neighbor_independent_substitution",
    "number_theoretic_filtering",
    "parallel_independent_substitution",
    "parallel_network_rewrite",
    "random_functional_graph_construction",
    "recursive_sequence",
    "sequential_substitution",
    "structural_pattern_rewrite",
    "substitution_system_2d",
    "symbolic_system",
    "tag_system",
    "variable_index_recursive_sequence",
    "enumerative_semidecision",
    "finite_gate_circuit",
    "mobile_automaton",
    "mobile_head_grid_rewrite",
    "nearest_neighbor_retrieval",
    "neighbor_updating_mobile_automaton",
    "recursive_function_evaluator",
    "register_machine",
    "stored_program_random_access_machine",
    "priority_dovetailed_oracle_construction",
    "turing_machine",
    "turing_machine_2d",
    "event_provenance_causal_network",
    "constant_digit_register",
    "digit_emitting_register_transduction",
    "error_diffusion_transform",
    "maximal_run_record_transduction",
    "hash_index_transform",
    "probabilistic_transition_model_fitting",
    "sampled_causal_order_network",
    "weighted_prefix_block_transduction",
    "nested_interval_symbol_transduction",
    "history_reference_record_transduction",
    "recursive_uniform_region_decomposition",
    "orthogonal_basis_coefficient_transform",
    "predictive_residual_transduction",
    "aligned_xor_stream_transduction",
    "look_and_say",
    "finite_model_satisfaction",
    "geometric_embedding_relation",
    "global_equation_relation",
    "inverse_local_system_reconstruction",
    "local_constraint_system",
    "local_factor_weighted_relation",
    "local_satisfaction_relation",
    "program_randomization_test",
    "seeded_template_constraint_system",
    "stochastic_local_search",
    "template_constraint_system",
    "weighted_history_sum_relation",
    "continuous_event_dynamics",
    "ordinary_differential_flow",
    "partial_differential_relation",
    "multiway_system",
    "network_rewrite",
    "pde",
)
