#!/usr/bin/env python3
"""Fail-closed primary-source audit for T33 required-template constraints.

This oracle audits evidence; it is not a tiling solver.  It freezes redundant
search lanes over the canonical monolithic Book, classifies every returned
line plus governed continuations, routes the actual Index, and reverse-joins
the split corpus.  Visuals are exposed only as a line-number interface to the
independent asset audit; no raster semantics are transcribed here.

The smallest source-faithful construction is the conjunction of T32's exact
allowed-local-pattern relation with one or more global existential occurrence
relations.  In the strict main profile a selected five-site cross template is
required to occur somewhere in the same static binary two-dimensional field.
"Shown at the center" is a witness-display/search convention: the defining
prose says somewhere, and a source example remains unique only modulo
translations.  It is not an initial configuration, fixed coordinate, firing
locus, write, update, or successor.
"""

from __future__ import annotations

import hashlib
import re
import sys
import unicodedata
from pathlib import Path


if not __debug__:
    raise RuntimeError("T33 source oracle requires assertions; do not use -O")


ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = ROOT / "ref/A-New-Kind-of-Science"
DEFAULT_BOOK = SOURCE_ROOT / "A-New-Kind-of-Science.md"
ATLAS = SOURCE_ROOT / "ANKoS-Atlas.md"
CATALOG = ROOT / "ref/notes/CA-Types.csv"
TAXONOMY = ROOT / "ref/notes/CA-Types.md"

INDEX_FIRST_LINE = 20826
EXPECTED_BOOK_LINES = 22498
EXPECTED_BOOK_SHA256 = "55537ca8cf7d99197b0e5ba043abbade76739e056e3b04b2f9eb6cf7e2ffee20"
EXPECTED_ATLAS_SHA256 = "5ffab93f0007bbeb5da60af7cc08570f9a358c9f9f94e37c5e00f9fc0997bc8a"
EXPECTED_CATALOG_SHA256 = "26cef05af1155f80bc301900d2df95469a90de027ba860730519d25d096c2b73"
EXPECTED_TAXONOMY_SHA256 = "4c30fe079b2fb8f69e4c8c0dde3d59065227d4224cbe4b7693a17c0126cc3f1a"


# Redundant direct, alias, mechanics, example, boundary, solver, relation,
# image, actual-Index, and modern-taxonomy guard lanes.  The broad lanes are
# intentional: every pre-Index false positive is explicitly dispositioned.
QUERIES = {
    "Q00": (
        r"particular template from this set must appear at least somewhere|"
        r"certain template from this set must occur at least once|"
        r"first template must appear at least somewhere|"
        r"first template appearing at least once|"
        r"every template in the set, must occur somewhere"
    ),
    "Q01": (
        r"at least somewhere in the pattern a template[^.]{0,160}must occur|"
        r"presence of a particular template at the center|"
        r"template that must occur is shown at the center"
    ),
    "Q02": (
        r"require not only that the colors around each cell match a set of templates|"
        r"not only must the arrangement of colors in each neighborhood match|"
        r"constraint, together with the requirement"
    ),
    "Q03": (
        r"137,438,953,472 constraints|1125528937|18762389|"
        r"4670324|373384574|387520105"
    ),
    "Q04": (
        r"simplest system based on constraints that is forced to exhibit a non-repetitive pattern|"
        r"only pattern that satisfies the constraint is the non-repetitive nested pattern|"
        r"Page 219 . Non-periodic pattern"
    ),
    "Q05": (
        r"build up patterns iteratively, starting with a small region|"
        r"extend patterns along a square spiral|"
        r"backtracking if the constraint|"
        r"no such direct procedure"
    ),
    "Q06": (
        r"fixed set of possible templates|"
        r"templates of neighboring cells overlapping|"
        r"set of allowed templates"
    ),
    "Q07": (
        r"increase the size of the templates|"
        r"increase the number of possible colors for each cell|"
        r"complete\s+\$?3 ?\\?times ?3\$?\s+blocks of cells|"
        r"3.times3\$?\s+templates"
    ),
    "Q08": (
        r"correspondence with the rule 60 elementary one-dimensional cellular automaton|"
        r"derived from the rule 30 cellular automaton|"
        r"shifted version of the one generated by the evolution of the rule 30"
    ),
    "Q09": (
        r"specify in advance a whole line of black and white cells|"
        r"specifies no cells in advance, or at most a few cells|"
        r"systems based on constraints do not have initial conditions"
    ),
    "Q10": (
        r"except for trivial translations|"
        r"origin of the x,y coordinates is the only freedom|"
        r"template[^.]{0,120}shown at the center"
    ),
    "Q11": (
        r"patterns are divided into several separate regions|"
        r"repeats in 98 . 98 blocks|"
        r"repeating every 56 cells on the diagonal"
    ),
    "Q12": (
        r"3.times3 templates with two colors extensive randomized searches|"
        r"not just a single template, but every template in the set|"
        r"searches of such systems have also failed"
    ),
    "Q13": (
        r"only the 33 templates shown above|"
        r"system with 56 allowed templates|"
        r"only the\s+\$56\.3 \\times 3\$\s+templates"
    ),
    "Q14": (
        r"12 templates shown, and that at least somewhere|"
        r"pair of stacked black cells|"
        r"specific set of 33 templates"
    ),
    "Q15": (
        r"_page_231_Picture_4\.jpeg|_page_233_Figure_1\.jpeg|"
        r"_page_234_Figure_2\.jpeg|_page_235_Picture_[46]\.jpeg|"
        r"_page_236_Picture_[12]\.jpeg"
    ),
    "Q16": (
        r"pattern forced by constraints, 22[01]|"
        r"tiling generating pattern of, 22[01]|"
        r"for non-periodic tilings, 220|"
        r"in satisfying constraints, 941"
    ),
    "Q17": r"seeded template constraint systems?|required global occurrence",
    "Q18": (
        r"constraints?[^.]{0,240}(?:appear at least|at least once|occur somewhere)|"
        r"(?:appear at least|at least once|occur somewhere)[^.]{0,240}constraints?"
    ),
    "Q19": (
        r"constraints?[^.]{0,240}force[^.]{0,180}patterns?|"
        r"patterns?[^.]{0,240}forced?[^.]{0,180}constraints?"
    ),
    "Q20": (
        r"allowed templates[^.]{0,220}first template|"
        r"first template[^.]{0,220}allowed templates|"
        r"template containing a pair of stacked black cells"
    ),
    "Q21": (
        r"specified no cells in advance|specifies no cells in advance|"
        r"at most a few cells, as in the systems discussed in the main text"
    ),
    "Q22": r"page 216|page 219|page 220|page 221",
    "Q23": (
        r"force complex patterns to occur|forced to exhibit behavior more complex|"
        r"force more complex behavior|force a nested pattern to occur|"
        r"complex and largely random pattern is forced to occur"
    ),
    "Q24": (
        r"millions of constraints, and tens of billions of candidate patterns|"
        r"after examining more than 18 million|"
        r"millions of these that I have tested"
    ),
    "Q25": (
        r"general problem of whether an infinite pattern exists|"
        r"no upper bound on the size of region|"
        r"finite region is NPcomplete"
    ),
    "Q26": (
        r"arrangement of colors around each cell must match one of|"
        r"only[^.]{0,100}templates shown[^.]{0,100}allowed to occur|"
        r"only[^.]{0,100}templates shown[^.]{0,100}occur anywhere"
    ),
    "Q27": r"systems? based on constraints",
    "Q28": (
        r"Satisfying constraints, 210.221|systems based on, 210.221|"
        r"Searching[^.]{0,700}to satisfy constraints, 343, 941"
    ),
    "Q29": (
        r"Relation to 1D cellular automata|"
        r"constraint can then be represented in terms of a set of allowed templates|"
        r"reproduce an ordinary picture of cellular automaton evolution"
    ),
    "Q30": (
        r"forcing nested patterns|non-computable patterns|"
        r"constraints[^.]{0,160}halting problem"
    ),
    "Q31": (
        r"Forcing of nested patterns, 942|"
        r"Non-computable patterns from constraints, 943"
    ),
}


def line_set(spec: str) -> frozenset[int]:
    result: set[int] = set()
    for item in filter(None, map(str.strip, spec.split(","))):
        if "-" in item:
            start, end = map(int, item.split("-", 1))
            result.update(range(start, end + 1))
        else:
            result.add(int(item))
    return frozenset(result)


# Every pre-Index query hit is classified exactly once.  Native is the strict
# singleton occurrence construction, its all-required Notes extension, and
# the source-backed larger-support instances.  Relations retain encodings and
# sibling constraint systems.  Controls preserve the T31/T32 base, solver
# boundary, and the decisive no-initial-condition statement.
NATIVE_MATCHED = line_set(
    "2634,2636,2638,2640,2662,2664,2666,2668,2670,2672,2674,2678,"
    "2680,2682,2684,2686,2688,2690,2692,2694,2696,14085,14095,14097"
)
RELATION_MATCHED = line_set(
    "4244,4324,5788,14099,14109,14115,14119,14121,14123,14130,"
    "14145,14146,15930,19274,20754"
)
CONTROL_MATCHED = line_set(
    "2568,2590,2594,2614,2618,2642,2646,2650,4046,6976,14027,"
    "14055,14080,14082,14083,14275,19816"
)

NATIVE_CONTINUATIONS = line_set("2632,2698,14087-14093")
RELATION_CONTINUATIONS = line_set(
    "5772,5776,5778,5780,5782,5784,5786,5790,5792,5794,6974,"
    "14111,14113,14117,14124,14126,14128,14132,14134,14136,14138,"
    "14140,14142,14144"
)
CONTROL_CONTINUATIONS = line_set(
    "1449,1451,1455,1457,1463,1465,1467,1481,1483,1487,1489,1493,1495,"
    "2570,2572,2574,2576,2578,2580,2582,2584,2586,2588,2592,2596,"
    "2598,2600,2602,2604,2606,2608,2610,2612,2616,2620,2626,2628,2630,"
    "2644,2648,2652,2654,2656,2658,2660,"
    "4030,4032,4040,4042,4044,"
    "14048,14050,14052,14054,14084"
)

NATIVE_EVIDENCE = NATIVE_MATCHED | NATIVE_CONTINUATIONS
RELATION_EVIDENCE = RELATION_MATCHED | RELATION_CONTINUATIONS
CONTROL_EVIDENCE = CONTROL_MATCHED | CONTROL_CONTINUATIONS
MATCHED_RETAINED = NATIVE_MATCHED | RELATION_MATCHED | CONTROL_MATCHED
GOVERNED_CONTINUATIONS = (
    NATIVE_CONTINUATIONS | RELATION_CONTINUATIONS | CONTROL_CONTINUATIONS
)
RETAINED = NATIVE_EVIDENCE | RELATION_EVIDENCE | CONTROL_EVIDENCE

# The deliberately broad discovery lanes return no pre-Index lexical false
# positive after relational and control evidence is dispositioned.
EXCLUDED_CLASS: dict[str, frozenset[int]] = {}
EXCLUDED = frozenset()


IMAGE_RE = re.compile(r"^!\[[^\]]*\]\(([^)]+)\)$")
NATIVE_IMAGE_LINES = line_set("2638,2662,2670,2682,2686,2690,2692")
RELATION_IMAGE_LINES = line_set("5786,6974,14111,14117,14136,14138,14142")
CONTROL_IMAGE_LINES = line_set(
    "1449,1455,1463,1465,1481,1487,1493,"
    "2576,2584,2598,2606,2616,2626,2628,"
    "4030,4040,4042,4044,14052"
)
GOVERNED_IMAGE_LINES = (
    NATIVE_IMAGE_LINES | RELATION_IMAGE_LINES | CONTROL_IMAGE_LINES
)
# Exact adjacent ownership guards: the preceding multiway plate, the first
# piecewise-number plate, and unrelated neighboring Notes plates are visible
# candidates but do not belong to T33 evidence.
EXCLUDED_IMAGE_CLASS = {
    "preceding_multiway": line_set("2564"),
    "following_piecewise_integer_map": line_set("1505"),
    "nearby_notes_non_T33": line_set("14162"),
}
EXCLUDED_IMAGE_LINES = frozenset().union(*EXCLUDED_IMAGE_CLASS.values())
CANDIDATE_IMAGE_LINES = GOVERNED_IMAGE_LINES | EXCLUDED_IMAGE_LINES


INDEX_CLASS = {
    "constraint_and_solver_routes": line_set("20908,21044,22080"),
    "forcing_and_noncomputability_routes": line_set("21193,21689"),
    "rule30_rule60_forced_pattern_routes": line_set("21994,21998"),
    "sibling_constraint_family_routes": line_set("22134,22146"),
}
INDEX_ROUTED = frozenset().union(*INDEX_CLASS.values())
INDEX_ENTRY_GUARDS = {
    "constraint_and_solver_routes": {
        20908: ("backtracking", "in satisfying constraints, 941"),
        21044: ("systems based on, 210-221", "producing complexity with"),
        22080: ("satisfying constraints, 210–221", "to satisfy constraints, 343, 941"),
    },
    "forcing_and_noncomputability_routes": {
        21193: ("forcing of nested patterns, 942",),
        21689: ("non-computable patterns from constraints, 943",),
    },
    "rule30_rule60_forced_pattern_routes": {
        21994: ("rule 30", "pattern forced by constraints, 221"),
        21998: ("rule 60", "pattern forced by constraints, 220"),
    },
    "sibling_constraint_family_routes": {
        22134: ("spin systems", "as systems based on constraints, 944"),
        22146: ("substitution systems", "systems based on constraints, 942"),
    },
}


VISUAL_ONLY_BOUNDARY = (
    "required-cross-gallery-and-centered-display",
    "gray-partial-search-stages",
    "nonperiodic-nested-witness-and-required-glyph",
    "larger-template-rule60-rule30-programs-and-witnesses",
    "formula-colors-and-coordinate-origin-not-pixel-decoded",
    "T31-T32-T34-sibling-and-relation-plates",
)


RAW_CORRUPT_RULE30_TEMPLATE_TEXT = r"$56.3 \times 3$"
SPLIT_RULE30_TEMPLATE_TEXT = "56 3 x 3 templates"
RAW_OPAQUE_FORMULA_PATTERN = "a[x_{-}, y_{-}]"


SOURCE_MODEL_RECORDS = (
    "category:static declarative model-set relation, not transition evolution",
    "strict-domain:binary discrete two-dimensional total field with no native time axis",
    "base:T32 finite exact allowed-local-pattern relation remains unchanged everywhere",
    "strict-requirement:one selected oriented five-site cross assignment",
    "quantifier:there exists at least one translated occurrence somewhere",
    "conjunction:local allowed relation and global required occurrence hold in the same field",
    "syntax-count:32 independent required-template choices times 2^32 allowed masks",
    "required-not-allowed:well-formed by full source count and semantically empty by conjunction",
    "numbering:printed decimal is the prior allowed-mask number and required template is separately displayed",
    "codec:no source-defined combined 37-bit integer order",
    "translation:centered figure and search are witness gauges, not a fixed semantic anchor",
    "identity:page-219 model is unique only modulo trivial translations",
    "witness:anchor belongs to verification or solver provenance, not model state",
    "repetition:T33 examples may be repetitive, nonrepetitive, satisfiable, or unsatisfiable",
    "search:gray partial assignments, propagation, choices, and backtracking are external solver state",
    "bounded-search:large finite extension need not imply an infinite model",
    "notes-formula:opaque denotation witness, not executable transition code",
    "extension:larger complete supports and more colors change only the T32 base relation",
    "all-required:finite conjunction with an independently existential anchor for each template",
    "CA-relation:rule60 and rule30 spacetime encodings are source mappings, not T33 evolution",
    "initial-condition:Book explicitly says systems based on constraints do not have initial conditions",
    "execution:no seed/frontier/read/write/update/successor/halting/runner branch",
    "source-defect:monolith 56.3-times-3 token is guarded against split 56 3-by-3 wording and 56-count prose",
    "source-defect:page-219 Mathematica blanks are extraction-corrupt and retained as opaque text only",
)


def digest(values: set[int] | frozenset[int]) -> str:
    payload = ",".join(map(str, sorted(values))).encode("ascii")
    return hashlib.sha256(payload).hexdigest()


def digest_records(records: set[str] | list[str] | tuple[str, ...]) -> str:
    payload = "\n".join(sorted(records)).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def normalized_line(line: str) -> str:
    text = unicodedata.normalize("NFKD", line).lower().replace("\\", "")
    return " ".join(re.findall(r"[a-z0-9]+", text))


def main() -> int:
    if len(sys.argv) > 2:
        raise SystemExit("usage: 41-T33-source-oracle.py [BOOK]")
    book = Path(sys.argv[1]).resolve() if len(sys.argv) == 2 else DEFAULT_BOOK
    raw = book.read_bytes()
    lines = raw.decode("utf-8").splitlines()
    source_ok = (
        len(lines) == EXPECTED_BOOK_LINES
        and hashlib.sha256(raw).hexdigest() == EXPECTED_BOOK_SHA256
        and sha256(ATLAS) == EXPECTED_ATLAS_SHA256
        and sha256(CATALOG) == EXPECTED_CATALOG_SHA256
        and sha256(TAXONOMY) == EXPECTED_TAXONOMY_SHA256
    )
    print("source", "OK" if source_ok else "MISMATCH")
    hits: dict[str, set[int]] = {}
    for name, pattern in QUERIES.items():
        found = {
            line_no
            for line_no, line in enumerate(lines, 1)
            if re.search(pattern, line, re.IGNORECASE)
        }
        hits[name] = found
        print(
            name,
            len(found),
            sum(n < INDEX_FIRST_LINE for n in found),
            sum(n >= INDEX_FIRST_LINE for n in found),
            digest(found),
            ",".join(map(str, sorted(found))),
        )
    union = set().union(*hits.values())
    pre = {n for n in union if n < INDEX_FIRST_LINE}
    index = union - pre
    print("union", len(union), digest(union), ",".join(map(str, sorted(union))))
    print("pre", len(pre), digest(pre), ",".join(map(str, sorted(pre))))
    print("index", len(index), digest(index), ",".join(map(str, sorted(index))))
    return 0 if source_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
