#!/usr/bin/env python3
"""Fail-closed primary-source audit for T33 required-template constraints.

This oracle audits evidence; it is not a tiling solver.  It freezes redundant
search lanes over the canonical monolithic Book, classifies every returned
line plus governed continuations, routes the actual Index, and reverse-joins
the split corpus.  Visuals are exposed only as a line-number interface to the
independent asset audit; no raster semantics are transcribed here.

The smallest source-faithful construction is the conjunction of T32's exact
allowed-local-pattern relation with one or more global existential occurrence
relations.  In the strict main profile a selected five-site cross template is
required to occur somewhere in the same static binary two-dimensional field.
"Shown at the center" is a witness-display/search convention: the defining
prose says somewhere, and a source example remains unique only modulo
translations.  It is not an initial configuration, fixed coordinate, firing
locus, write, update, or successor.
"""

from __future__ import annotations

import hashlib
import re
import sys
import unicodedata
from pathlib import Path


if not __debug__:
    raise RuntimeError("T33 source oracle requires assertions; do not use -O")


ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = ROOT / "ref/A-New-Kind-of-Science"
DEFAULT_BOOK = SOURCE_ROOT / "A-New-Kind-of-Science.md"
ATLAS = SOURCE_ROOT / "ANKoS-Atlas.md"
CATALOG = ROOT / "ref/notes/CA-Types.csv"
TAXONOMY = ROOT / "ref/notes/CA-Types.md"

INDEX_FIRST_LINE = 20826
EXPECTED_BOOK_LINES = 22498
EXPECTED_BOOK_SHA256 = "55537ca8cf7d99197b0e5ba043abbade76739e056e3b04b2f9eb6cf7e2ffee20"
EXPECTED_ATLAS_SHA256 = "5ffab93f0007bbeb5da60af7cc08570f9a358c9f9f94e37c5e00f9fc0997bc8a"
EXPECTED_CATALOG_SHA256 = "26cef05af1155f80bc301900d2df95469a90de027ba860730519d25d096c2b73"
EXPECTED_TAXONOMY_SHA256 = "4c30fe079b2fb8f69e4c8c0dde3d59065227d4224cbe4b7693a17c0126cc3f1a"


# Redundant direct, alias, mechanics, example, boundary, solver, relation,
# image, actual-Index, and modern-taxonomy guard lanes.  The broad lanes are
# intentional: every pre-Index false positive is explicitly dispositioned.
QUERIES = {
    "Q00": (
        r"particular template from this set must appear at least somewhere|"
        r"certain template from this set must occur at least once|"
        r"first template must appear at least somewhere|"
        r"first template appearing at least once|"
        r"every template in the set, must occur somewhere"
    ),
    "Q01": (
        r"at least somewhere in the pattern a template[^.]{0,160}must occur|"
        r"presence of a particular template at the center|"
        r"template that must occur is shown at the center"
    ),
    "Q02": (
        r"require not only that the colors around each cell match a set of templates|"
        r"not only must the arrangement of colors in each neighborhood match|"
        r"constraint, together with the requirement"
    ),
    "Q03": (
        r"137,438,953,472 constraints|1125528937|18762389|"
        r"4670324|373384574|387520105"
    ),
    "Q04": (
        r"simplest system based on constraints that is forced to exhibit a non-repetitive pattern|"
        r"only pattern that satisfies the constraint is the non-repetitive nested pattern|"
        r"Page 219 . Non-periodic pattern"
    ),
    "Q05": (
        r"build up patterns iteratively, starting with a small region|"
        r"extend patterns along a square spiral|"
        r"backtracking if the constraint|"
        r"no such direct procedure"
    ),
    "Q06": (
        r"fixed set of possible templates|"
        r"templates of neighboring cells overlapping|"
        r"set of allowed templates"
    ),
    "Q07": (
        r"increase the size of the templates|"
        r"increase the number of possible colors for each cell|"
        r"complete\s+\$?3 ?\\?times ?3\$?\s+blocks of cells|"
        r"3.times3\$?\s+templates"
    ),
    "Q08": (
        r"correspondence with the rule 60 elementary one-dimensional cellular automaton|"
        r"derived from the rule 30 cellular automaton|"
        r"shifted version of the one generated by the evolution of the rule 30"
    ),
    "Q09": (
        r"specify in advance a whole line of black and white cells|"
        r"specifies no cells in advance, or at most a few cells|"
        r"systems based on constraints do not have initial conditions"
    ),
    "Q10": (
        r"except for trivial translations|"
        r"origin of the x,y coordinates is the only freedom|"
        r"template[^.]{0,120}shown at the center"
    ),
    "Q11": (
        r"patterns are divided into several separate regions|"
        r"repeats in 98 . 98 blocks|"
        r"repeating every 56 cells on the diagonal"
    ),
    "Q12": (
        r"3.times3 templates with two colors extensive randomized searches|"
        r"not just a single template, but every template in the set|"
        r"searches of such systems have also failed"
    ),
    "Q13": (
        r"only the 33 templates shown above|"
        r"system with 56 allowed templates|"
        r"only the\s+\$56\.3 \\times 3\$\s+templates"
    ),
    "Q14": (
        r"12 templates shown, and that at least somewhere|"
        r"pair of stacked black cells|"
        r"specific set of 33 templates"
    ),
    "Q15": (
        r"_page_231_Picture_4\.jpeg|_page_233_Figure_1\.jpeg|"
        r"_page_234_Figure_2\.jpeg|_page_235_Picture_[46]\.jpeg|"
        r"_page_236_Picture_[12]\.jpeg"
    ),
    "Q16": (
        r"pattern forced by constraints, 22[01]|"
        r"tiling generating pattern of, 22[01]|"
        r"for non-periodic tilings, 220|"
        r"in satisfying constraints, 941"
    ),
    "Q17": r"seeded template constraint systems?|required global occurrence",
    "Q18": (
        r"constraints?[^.]{0,240}(?:appear at least|at least once|occur somewhere)|"
        r"(?:appear at least|at least once|occur somewhere)[^.]{0,240}constraints?"
    ),
    "Q19": (
        r"constraints?[^.]{0,240}force[^.]{0,180}patterns?|"
        r"patterns?[^.]{0,240}forced?[^.]{0,180}constraints?"
    ),
    "Q20": (
        r"allowed templates[^.]{0,220}first template|"
        r"first template[^.]{0,220}allowed templates|"
        r"template containing a pair of stacked black cells"
    ),
    "Q21": (
        r"specified no cells in advance|specifies no cells in advance|"
        r"at most a few cells, as in the systems discussed in the main text"
    ),
    "Q22": r"page 216|page 219|page 220|page 221",
    "Q23": (
        r"force complex patterns to occur|forced to exhibit behavior more complex|"
        r"force more complex behavior|force a nested pattern to occur|"
        r"complex and largely random pattern is forced to occur"
    ),
    "Q24": (
        r"millions of constraints, and tens of billions of candidate patterns|"
        r"after examining more than 18 million|"
        r"millions of these that I have tested"
    ),
    "Q25": (
        r"general problem of whether an infinite pattern exists|"
        r"no upper bound on the size of region|"
        r"finite region is NPcomplete"
    ),
    "Q26": (
        r"arrangement of colors around each cell must match one of|"
        r"only[^.]{0,100}templates shown[^.]{0,100}allowed to occur|"
        r"only[^.]{0,100}templates shown[^.]{0,100}occur anywhere"
    ),
    "Q27": r"systems? based on constraints",
    "Q28": (
        r"Satisfying constraints, 210.221|systems based on, 210.221|"
        r"Searching[^.]{0,700}to satisfy constraints, 343, 941"
    ),
    "Q29": (
        r"Relation to 1D cellular automata|"
        r"constraint can then be represented in terms of a set of allowed templates|"
        r"reproduce an ordinary picture of cellular automaton evolution"
    ),
    "Q30": (
        r"forcing nested patterns|non-computable patterns|"
        r"constraints[^.]{0,160}halting problem"
    ),
    "Q31": (
        r"Forcing of nested patterns, 942|"
        r"Non-computable patterns from constraints, 943"
    ),
}


def line_set(spec: str) -> frozenset[int]:
    result: set[int] = set()
    for item in filter(None, map(str.strip, spec.split(","))):
        if "-" in item:
            start, end = map(int, item.split("-", 1))
            result.update(range(start, end + 1))
        else:
            result.add(int(item))
    return frozenset(result)


# Every pre-Index query hit is classified exactly once.  Native is the strict
# singleton occurrence construction, its all-required Notes extension, and
# the source-backed larger-support instances.  Relations retain encodings and
# sibling constraint systems.  Controls preserve the T31/T32 base, solver
# boundary, and the decisive no-initial-condition statement.
NATIVE_MATCHED = line_set(
    "2634,2636,2638,2640,2662,2664,2666,2668,2670,2672,2674,2678,"
    "2680,2682,2684,2686,2688,2690,2692,2694,2696,14085,14095,14097"
)
RELATION_MATCHED = line_set(
    "4244,4324,5788,14099,14109,14115,14119,14121,14123,14130,"
    "14145,14146,15930,19274,20754"
)
CONTROL_MATCHED = line_set(
    "2568,2590,2594,2614,2618,2642,2646,2650,4046,6976,14027,"
    "14055,14080,14082,14083,14275,19816"
)

NATIVE_CONTINUATIONS = line_set("2632,2698,14087-14093")
RELATION_CONTINUATIONS = line_set(
    "2322,"
    "4068,4070,4072,4074,4076,4078,4080,4082,4084,"
    "5772,5776,5778,5780,5782,5784,5786,5790,5792,5794,6974,"
    "14111,14113,14117,14124,14126,14128,14132,14134,14136,14138,"
    "14140,14142,14144"
)
CONTROL_CONTINUATIONS = line_set(
    "1449,1451,1455,1457,1463,1465,1467,1481,1483,1487,1489,1493,1495,"
    "2570,2572,2574,2576,2578,2580,2582,2584,2586,2588,2592,2596,"
    "2598,2600,2602,2604,2606,2608,2610,2612,2616,2620,2626,2628,2630,"
    "2644,2648,2652,2654,2656,2658,2660,"
    "3980,3982,3984,3986,3988,3990,3992,3996,3998,"
    "4000,4002,4004,4006,4008,4010,4012,4014,4016,4018,4020,4022,4024,"
    "4026,4028,4030,4032,4034,4036,4038,4040,4042,4044,4048,4050,"
    "4052,4054,4056,4058,4060,4062,4064,4066,"
    "14048,14050,14052,14054,14084"
)

NATIVE_EVIDENCE = NATIVE_MATCHED | NATIVE_CONTINUATIONS
RELATION_EVIDENCE = RELATION_MATCHED | RELATION_CONTINUATIONS
CONTROL_EVIDENCE = CONTROL_MATCHED | CONTROL_CONTINUATIONS
MATCHED_RETAINED = NATIVE_MATCHED | RELATION_MATCHED | CONTROL_MATCHED
GOVERNED_CONTINUATIONS = (
    NATIVE_CONTINUATIONS | RELATION_CONTINUATIONS | CONTROL_CONTINUATIONS
)
RETAINED = NATIVE_EVIDENCE | RELATION_EVIDENCE | CONTROL_EVIDENCE

# The deliberately broad discovery lanes return no pre-Index lexical false
# positive after relational and control evidence is dispositioned.
EXCLUDED_CLASS: dict[str, frozenset[int]] = {}
EXCLUDED = frozenset()


IMAGE_RE = re.compile(r"^!\[[^\]]*\]\(([^)]+)\)$")
NATIVE_IMAGE_LINES = line_set("2638,2662,2670,2682,2686,2690,2692")
RELATION_IMAGE_LINES = line_set(
    "2322,4074,4076,4080,5786,6974,14111,14117,14136,14138,14142"
)
CONTROL_IMAGE_LINES = line_set(
    "1449,1455,1463,1465,1481,1487,1493,"
    "2576,2584,2598,2606,2616,2626,2628,"
    "4000,4002,4018,4022,4030,4040,4042,4044,4058,14052"
)
GOVERNED_IMAGE_LINES = (
    NATIVE_IMAGE_LINES | RELATION_IMAGE_LINES | CONTROL_IMAGE_LINES
)
# Exact adjacent ownership guards: the preceding multiway plate, the first
# piecewise-number plate, and unrelated neighboring Notes plates are visible
# candidates but do not belong to T33 evidence.
EXCLUDED_IMAGE_CLASS = {
    "substitution_and_geometric_neighbors": line_set("2314,2328,2330"),
    "preceding_multiway": line_set("2564"),
    "following_piecewise_integer_map": line_set("1505"),
    "nearby_notes_Diophantine_assembly": line_set("14162,14164,14166,14168"),
    "preceding_CA_motion_plate": line_set("14273"),
}
EXCLUDED_IMAGE_LINES = frozenset().union(*EXCLUDED_IMAGE_CLASS.values())
CANDIDATE_IMAGE_LINES = GOVERNED_IMAGE_LINES | EXCLUDED_IMAGE_LINES


INDEX_CLASS = {
    "constraint_and_solver_routes": line_set("20908,21044,22080"),
    "forcing_and_noncomputability_routes": line_set("21193,21689"),
    "rule30_rule60_forced_pattern_routes": line_set("21994,21998"),
    "sibling_constraint_family_routes": line_set("22134,22146"),
}
INDEX_ROUTED = frozenset().union(*INDEX_CLASS.values())
INDEX_ENTRY_GUARDS = {
    "constraint_and_solver_routes": {
        20908: ("backtracking", "in satisfying constraints, 941"),
        21044: ("systems based on, 210-221", "producing complexity with"),
        22080: ("satisfying constraints, 210–221", "to satisfy constraints, 343, 941"),
    },
    "forcing_and_noncomputability_routes": {
        21193: ("forcing of nested patterns, 942",),
        21689: ("non-computable patterns from constraints, 943",),
    },
    "rule30_rule60_forced_pattern_routes": {
        21994: ("rule 30", "pattern forced by constraints, 221"),
        21998: ("rule 60", "pattern forced by constraints, 220"),
    },
    "sibling_constraint_family_routes": {
        22134: ("spin systems", "as systems based on constraints, 944"),
        22146: ("substitution systems", "systems based on constraints, 942"),
    },
}


VISUAL_ONLY_BOUNDARY = (
    "required-cross-gallery-and-centered-display",
    "gray-partial-search-stages",
    "nonperiodic-nested-witness-and-required-glyph",
    "larger-template-rule60-rule30-programs-and-witnesses",
    "formula-colors-and-coordinate-origin-not-pixel-decoded",
    "T31-T32-T34-sibling-and-relation-plates",
)


RAW_CORRUPT_RULE30_TEMPLATE_TEXT = r"$56.3 \times 3$"
SPLIT_RULE30_TEMPLATE_TEXT = "56 3 x 3 templates"
RAW_OPAQUE_FORMULA_PATTERN = "a[x_{-}, y_{-}]"


SOURCE_MODEL_RECORDS = (
    "category:static declarative model-set relation, not transition evolution",
    "strict-domain:binary discrete two-dimensional total field with no native time axis",
    "base:T32 finite exact allowed-local-pattern relation remains unchanged everywhere",
    "strict-requirement:one selected oriented five-site cross assignment",
    "quantifier:there exists at least one translated occurrence somewhere",
    "conjunction:local allowed relation and global required occurrence hold in the same field",
    "syntax-count:32 independent required-template choices times 2^32 allowed masks",
    "required-not-allowed:well-formed by full source count and semantically empty by conjunction",
    "numbering:printed decimal is the prior allowed-mask number and required template is separately displayed",
    "codec:no source-defined combined 37-bit integer order",
    "translation:centered figure and search are witness gauges, not a fixed semantic anchor",
    "identity:page-219 model is unique only modulo trivial translations",
    "witness:anchor belongs to verification or solver provenance, not model state",
    "repetition:T33 examples may be repetitive, nonrepetitive, satisfiable, or unsatisfiable",
    "search:gray partial assignments, propagation, choices, and backtracking are external solver state",
    "bounded-search:large finite extension need not imply an infinite model",
    "notes-formula:opaque denotation witness, not executable transition code",
    "extension:larger complete supports and more colors change only the T32 base relation",
    "all-required:finite conjunction with an independently existential anchor for each template",
    "CA-relation:rule60 and rule30 spacetime encodings are source mappings, not T33 evolution",
    "initial-condition:Book explicitly says systems based on constraints do not have initial conditions",
    "execution:no seed/frontier/read/write/update/successor/halting/runner branch",
    "source-defect:monolith 56.3-times-3 token is guarded against split 56 3-by-3 wording and 56-count prose",
    "source-defect:page-219 Mathematica blanks are extraction-corrupt and retained as opaque text only",
)


EXPECTED_QUERY = {
    "Q00": (5, 5, 0, "0e36502fa4c8671867ed8af6085913368ab9f8c9bd28c05cd11504b55fd0a694"),
    "Q01": (3, 3, 0, "6c37539f92bb477ac63100d3f4af3f61b1ba63492e5ccfaa0e4d35caf3b2e2c2"),
    "Q02": (3, 3, 0, "deaa52c5cd737947f9c4ce688d9b03f7a6b9fa22890c10e7a9d4122f04534db9"),
    "Q03": (4, 4, 0, "f7d07ccb288daafbd9e49ef8d1c7bd6c6287064dcd226e3e06337a51fa1587cb"),
    "Q04": (3, 3, 0, "c6660008caac46df11c9e92711a0296c848aca4c27f961ed0e4495b6da6fbdcf"),
    "Q05": (3, 3, 0, "95e3201d510661f8e12ea8ff778cce1956c142ef1af1852390502c2287615a41"),
    "Q06": (4, 4, 0, "eead4a1f256c8e516952abbdc9894db4de5a63a2bd3ad82853b320d51314458e"),
    "Q07": (3, 3, 0, "073913f6e855aabe72651166f01b145f56b71b5f3cd60748823d77e3976d47d0"),
    "Q08": (3, 3, 0, "09cf2a88fb23d249af42e3a002c2ed058906ceba22e1d523ffc600f91dd4e4c4"),
    "Q09": (3, 3, 0, "f942967307787bfd5feab25bbb1188901498ddfae7191079eab1c7d8d0da3ade"),
    "Q10": (3, 3, 0, "364b9d13feff5ffbc2982cc0f8fe2938ada08bd6edf6324f87449465be83e28a"),
    "Q11": (2, 2, 0, "12bf04affa84ca3101acd19f3acd6abd49c36665ef1c7c818edc82c157a58013"),
    "Q12": (1, 1, 0, "0d89b2b31f97c14550cbb4dce99493abcd983962abddc28ee00e42b5b19556d7"),
    "Q13": (3, 3, 0, "09cf2a88fb23d249af42e3a002c2ed058906ceba22e1d523ffc600f91dd4e4c4"),
    "Q14": (2, 2, 0, "9c43001d95b59467d6b9a70dd8cbf5b744ef267ce316cc4b22dc58dda1765186"),
    "Q15": (7, 7, 0, "bf5973e5ca2bde537bb80ccce7088f447f407f85751c4431becbf97a776c2728"),
    "Q16": (4, 0, 4, "a742ef8103137f5514aa06d23fba28ebf47524b2f5e476847e3757263691d469"),
    "Q17": (0, 0, 0, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"),
    "Q18": (2, 2, 0, "5e79db636932b55301454d3c228753b23c9cc69cc915d48537f2f6ffa5e1c7c4"),
    "Q19": (12, 10, 2, "58194e38da461c0bd205eb2e407b21b5747601a1df0a0ddbeef8c582c14d6953"),
    "Q20": (1, 1, 0, "48edac0718a29c1157a2e5f12944c2b7205e6b7be4d80cb5b731255a756f8df4"),
    "Q21": (1, 1, 0, "965fb140d7e15df5f1364a8631a6a2c8c8b5bddeb28f009013c9713b0d249d0f"),
    "Q22": (5, 5, 0, "1104b248a89d7eb11e493b98d254e34d87e1ce9496042c213bf98faae2675fd7"),
    "Q23": (5, 5, 0, "b49e599b49d1e8df8dda2ebcb54c3ecda8b873c6da9a91c2513771856093d2a5"),
    "Q24": (3, 3, 0, "8e9b01140689aa3268da68461e9fda65f6f8cc57566b9d5519da6c696510ef8e"),
    "Q25": (2, 2, 0, "895ba8bf29d93b3fbf882ad2af4deb1a0271d3c62bd8a0834b8477c36e24937c"),
    "Q26": (2, 2, 0, "6f3e0be72ef9d4fdc586324b9e90417694415aa82ce2ee0bbdb859c21343057c"),
    "Q27": (17, 15, 2, "e20f31a102695f2d3dae11df65b55d215b9d7721f6e3fc321e80facb1a4f8fb0"),
    "Q28": (2, 0, 2, "1fff8533eb5204a9d93624dba929a7378fbf2debad46e17b59ac6eb88b530f91"),
    "Q29": (2, 2, 0, "9cccb3003ef0f8381345059a3b23d4102d6b8c8b9962e23b454dc9f60186ba4b"),
    "Q30": (3, 2, 1, "f3e685c72a0ded3e07a1683c14320859d6697e8b07b4a658da14a3c0abf3a7cb"),
    "Q31": (2, 0, 2, "af5e23967232ae99e866d3ecb87075e6f9c72fc100f6191c86ece39c0b9b9ff4"),
}


# Set and reverse-provenance expectations are frozen below.  Split values are
# initially populated by the same independently recomputed joins and then
# asserted on every run.
EXPECTED_SET = {
    "union": (65, "dd8d78b91013455349b559208a61518c70a8f5655d586b10c0c980830fb379d7"),
    "pre_index_union": (56, "c9375acb70efa7f27d3e7b377d5dd61b256cc90befc099644145afdf4ed803df"),
    "index": (9, "0962f5c2dec055c54558ca3867eb311568fc00f655793238cd34e52625793ad1"),
    "matched_retained": (56, "c9375acb70efa7f27d3e7b377d5dd61b256cc90befc099644145afdf4ed803df"),
    "governed_continuations": (135, "214b1a02c96518655b49788c4e2d6c74d8f82afc60a7094cc73ba3695507eea5"),
    "retained": (191, "4ab65fc37aec80cf9a9d3653a2c157b62d1be73f6b5d89c9ac111ac6678c0349"),
    "excluded": (0, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"),
    "native": (33, "0d1238f4e90f680efd5248b597714121fb4b2af758b3210e54102a36b8e77c85"),
    "relation": (49, "31bd61311f7019d478febfc9ebd85784e0274bf62a96b0f75fb3af210081821b"),
    "control": (109, "b3b2d5755dbbeaf16667dc322d21c4455b90ee4f52bef6874a6dc1e235413e80"),
    "candidate_images": (52, "67101b858031d5cfcb3c0532588f11732ad9d5bccd6db5f942a84268c8521bd5"),
    "governed_images": (42, "fd6f90fc2c6f07a8e8c56e62eaa268545cbfc5d1024169c95c972cd97f9dcd97"),
    "excluded_images": (10, "79ae511b0f04d2ac136061d8ff6e97d30cc5c135091cac2ca5b6afcf8250bbb5"),
}
EXPECTED_INDEX_CLASS = {
    "constraint_and_solver_routes": (3, "2f6ab7d02ca4c2c6c54e28f1f3ff804919d837a55b4e563aa8ccf0ba3cfb9a95"),
    "forcing_and_noncomputability_routes": (2, "af5e23967232ae99e866d3ecb87075e6f9c72fc100f6191c86ece39c0b9b9ff4"),
    "rule30_rule60_forced_pattern_routes": (2, "14c3e7058a177043f01b50e3bbdb3bcb6409d6c160017cd1ab4c03e38e5dc2e5"),
    "sibling_constraint_family_routes": (2, "652197ba4bfd4fa73c7ef5895aa82ceb1223c7f6df5571458699602ace14ff71"),
}
EXPECTED_INDEX_GUARDS = (9, "fd34a85f29b0a4d23ccecbd98fe7ae37b2253b2c3a30e7f7100b220fcd92d64a")
EXPECTED_IMAGE_PARTITION = {
    "native": (7, "bf5973e5ca2bde537bb80ccce7088f447f407f85751c4431becbf97a776c2728"),
    "relation": (11, "bf854a24144520fd1400d906459a8bf243dcfc24cc2b014c770bdf4c1c0e6823"),
    "control": (24, "b6f5545069072356892c7bd2249f4e4ca7387109ded74dc44196f819a85c5fee"),
}
EXPECTED_EXCLUDED_IMAGE_CLASS = {
    "substitution_and_geometric_neighbors": (3, "4127f8c8599df6e70a62c277c0a6aad51e4cc8828e231cdd0714e5c459a8a21c"),
    "preceding_multiway": (1, "d0c9e369bee256f4b0182a503babb685ee7b00419c985fb423a47bfb0eb89f56"),
    "following_piecewise_integer_map": (1, "755917ecbc61091ffa6b605d7f82bdaa4e4cbdc309124807b0fb63228d0696df"),
    "nearby_notes_Diophantine_assembly": (4, "bed722234648c726993140640203cb9d5e6a9c16fc1427316c37dc27ce33642e"),
    "preceding_CA_motion_plate": (1, "214ed1d843bba0884f63f3d4b9ab9e7ec2f3d6f635f7522fff4c0e70c37d6ec0"),
}
EXPECTED_VISUAL_ONLY_BOUNDARY = (
    6,
    "a89a615c48474935708dc424eda0354e327933309470f97e7cd3fc3cf2dfe230",
)

EXPECTED_SPLIT_FILE_COUNT = 17
EXPECTED_SPLIT_PATHS_DIGEST = "409ee97767cd31136d0d647ac9f1d4555fa6154e20a3cd620baaa915d1bf6692"
EXPECTED_SPLIT_MANIFEST_DIGEST = "55a03f55f7c609afc197dc37f38bc25081b90502e720ed7210335deee15a9a84"
EXPECTED_SPLIT_QUERY = (0, "")
EXPECTED_SPLIT_QUERY_EXACT = (0, "")
EXPECTED_SPLIT_QUERY_NONEXACT = (0, "")
EXPECTED_SPLIT_QUERY_MAPPING = (0, "")
EXPECTED_SPLIT_RETAINED_EXACT = (0, "")
EXPECTED_SPLIT_RETAINED_NONEXACT = (0, "")
EXPECTED_SPLIT_RETAINED_MAPPING = (0, "")
EXPECTED_MONOLITH_ONLY = (
    0,
    "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
)
EXPECTED_ATLAS_HITS = (
    2,
    "dd39606da577b951d544e3e059f492e5932d034f4cd462fcb22e29b1a77f93ed",
)
EXPECTED_SOURCE_MODEL = (
    24,
    "c00fee3f69f5d7ec669ec7a4eb1d3b636680f10e42056735b2798708be6aa0b1",
)


def digest(values: set[int] | frozenset[int]) -> str:
    payload = ",".join(map(str, sorted(values))).encode("ascii")
    return hashlib.sha256(payload).hexdigest()


def digest_records(records: set[str] | list[str] | tuple[str, ...]) -> str:
    payload = "\n".join(sorted(records)).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def normalized_line(line: str) -> str:
    text = unicodedata.normalize("NFKD", line).lower().replace("\\", "")
    return " ".join(re.findall(r"[a-z0-9]+", text))


def best_witness(canonical: str, candidates: list[tuple[str, str]]) -> tuple[str, float]:
    canonical_tokens = set(normalized_line(canonical).split())
    scored: list[tuple[float, str]] = []
    for record, normalized in candidates:
        candidate_tokens = set(normalized.split())
        denominator = min(len(canonical_tokens), len(candidate_tokens))
        score = len(canonical_tokens & candidate_tokens) / denominator if denominator else 0.0
        scored.append((score, record))
    score, record = max(scored, key=lambda item: (item[0], item[1]))
    return record, score


def main() -> int:
    if len(sys.argv) > 2:
        raise SystemExit("usage: 41-T33-source-oracle.py [BOOK]")
    book = Path(sys.argv[1]).resolve() if len(sys.argv) == 2 else DEFAULT_BOOK
    raw = book.read_bytes()
    lines = raw.decode("utf-8").splitlines()
    source_ok = (
        len(lines) == EXPECTED_BOOK_LINES
        and hashlib.sha256(raw).hexdigest() == EXPECTED_BOOK_SHA256
        and sha256(ATLAS) == EXPECTED_ATLAS_SHA256
        and sha256(CATALOG) == EXPECTED_CATALOG_SHA256
        and sha256(TAXONOMY) == EXPECTED_TAXONOMY_SHA256
    )
    print("source", "OK" if source_ok else "MISMATCH")
    hits: dict[str, set[int]] = {}
    for name, pattern in QUERIES.items():
        found = {
            line_no
            for line_no, line in enumerate(lines, 1)
            if re.search(pattern, line, re.IGNORECASE)
        }
        hits[name] = found
        print(
            name,
            len(found),
            sum(n < INDEX_FIRST_LINE for n in found),
            sum(n >= INDEX_FIRST_LINE for n in found),
            digest(found),
            ",".join(map(str, sorted(found))),
        )
    union = set().union(*hits.values())
    pre = {n for n in union if n < INDEX_FIRST_LINE}
    index = union - pre
    print("union", len(union), digest(union), ",".join(map(str, sorted(union))))
    print("pre", len(pre), digest(pre), ",".join(map(str, sorted(pre))))
    print("index", len(index), digest(index), ",".join(map(str, sorted(index))))
    return 0 if source_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
